version: '3'
services:
  # Your other services should appear here. Ensure that the service you want to restart is named the same as the CONTAINER env below, and that
  # container_name is explicitly set (not just implied by the service name) to avoid issues with docker-compose's container naming scheme.
  spotifyd:
    container_name: spotifyd
    ...
  
  restarter:
    image: dockercron
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    environment:
      # Restart every day at 6:30
      - CRONFREQ=30 06 * * *
      - CONTAINER=spotifyd
    restart: unless-stopped